import { Layout } from "@/layout/dashboard/layout"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <div>
        <Layout>
            {children}
        </Layout>
    </div>
  )
}
