import NavBar from "@/components/NavBar/NavBar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <div>
        <NavBar/>
        <div style={{marginTop: "20px"}}>
        {children}
        </div>
    </div>
  )
}
